-- Token analysis reports (generated by Claude from official Twitter posts)
-- One row per token. Report is refreshed if older than 7 days.

CREATE TABLE token_reports (
    id            INT IDENTITY(1,1) PRIMARY KEY,
    token_address NVARCHAR(42)  NOT NULL,
    report        NVARCHAR(MAX) NOT NULL,
    tweet_count   INT           NOT NULL DEFAULT 0,
    generated_at  DATETIME2     NOT NULL DEFAULT GETDATE(),
);

CREATE UNIQUE INDEX UQ_token_reports_address
    ON token_reports(token_address);
