"""
Token Report Service — reads x_report directly from graduated_tokens.

All reports are pre-generated by scripts/score_tokens.py (batch Grok scorer).
No live API calls, no secondary cache table.
"""

import logging

from ..database import get_db

logger = logging.getLogger(__name__)


async def get_or_create_report(token_address: str) -> dict | None:
    """
    Return the Grok-scored report for this token from graduated_tokens.
    Returns None if the token hasn't been scored yet.
    """
    token_address = token_address.lower()

    try:
        with get_db() as conn:
            cur = conn.cursor()
            cur.execute("""
                SELECT x_report, x_score, x_scored_at
                FROM graduated_tokens
                WHERE address = ?
                  AND x_report IS NOT NULL
            """, token_address)
            row = cur.fetchone()

        if row:
            logger.info(f"[report] hit for {token_address} (score={row[1]})")
            return {
                "report":       row[0],
                "score":        row[1],
                "generated_at": row[2].isoformat() if row[2] else None,
            }

    except Exception as exc:
        logger.warning(f"[report] DB lookup failed: {exc}")

    logger.info(f"[report] no report found for {token_address}")
    return None
